name: router_demo
dependencies:
  angular2: "2.0.0-alpha.31"
  browser: "0.10.0+2"
transformers:
- angular2:
    entry_points:
        - web/main.dart
    reflection_entry_points:
        - web/main.dart
- $dart2js:
    minify: true
    commandLineOptions:
    - --dump-info
    - --show-package-warnings
    - --trust-type-annotations
    - --trust-primitives